#!/usr/bin/env python3
"""
15_oracle_expansion.py

Run from the folder that CONTAINS the v12A1 working folder.

Expands the mpmath oracle to validate v12A1 additions:
  - gamma / lgamma (Lanczos)
  - pow (extended precision + integer fast path)
  - large-argument trig (Payne-Hanek)

Targets:
    v12A1/scripts/oracles/generate_oracles.py
    v12A1/tests/oracle_data.h  (regenerated)
    v12A1/tests/test_oracle.c

Requires:
    pip install mpmath

Usage:
    python3 15_oracle_expansion.py
    python3 15_oracle_expansion.py --force
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

MARKER = "MATHLIB_V12A1_ORACLE_EXPANSION"

NEW_GENERATE_ORACLES = r'''#!/usr/bin/env python3
"""
generate_oracles.py — v12A1 expanded oracle generator.

Generates ground-truth data for:
  sin, cos, exp, log (original v11S set)
  gamma, lgamma (v12A1 Lanczos)
  pow (v12A1 extended precision)
  large-argument sin/cos (v12A1 Payne-Hanek)

Requires: pip install mpmath
"""
import sys

try:
    from mpmath import mp, mpf, sin, cos, exp, log, gamma, power, pi, ln
except ImportError:
    print("ERROR: mpmath not installed. Run: pip install mpmath")
    sys.exit(1)

mp.dps = 50

# --- Original v11S trig inputs ---
trig_inputs = [
    0.0, 0.5, 1.0, 1.5, 2.0, 3.0, 3.141592653589793,
    -0.5, -1.0, -1.5, -2.0, -3.0, -3.141592653589793,
    6.283185307179586, 10.0, 100.0, 1000.0, 10000.0, 1000000.0,
    1e-10, 1e-50, 1e-100, 1e-200, 1e-300,
    -1e-10, -1e-50, -1e-100,
    0.1, 0.01, 0.001, 0.0001,
    7.0, 8.0, 9.0, 10.5, 15.0, 20.0, 50.0,
]

# --- v12A1: large-argument trig (Payne-Hanek) ---
large_trig_inputs = [1e10, 1e15, 1e20, 1e50, 1e100, 1e200, 1e300]

# --- Original v11S exp/log inputs ---
pos_inputs = [
    0.5, 1.0, 1.5, 2.0, 3.0, 5.0, 10.0, 100.0,
    1e-10, 1e-50, 1e-100, 1e-200, 1e-300,
    1e10, 1e50, 1e100, 1e200, 1e300,
    0.1, 0.01, 0.001,
    2.718281828459045, 0.6931471805599453,
]

# --- v12A1: gamma inputs ---
gamma_inputs = [
    0.5, 1.0, 1.5, 2.0, 3.0, 4.0, 5.0, 6.0, 10.0, 20.0, 50.0, 100.0, 171.0,
    0.1, 0.01, 0.001,
    -0.5, -1.5, -2.5, -3.5, -0.1, -0.9,
]

# --- v12A1: lgamma inputs ---
lgamma_inputs = [
    0.5, 1.0, 1.5, 2.0, 3.0, 5.0, 10.0, 50.0, 100.0, 171.0,
    0.1, 0.01,
    -0.5, -1.5, -2.5, -0.1,
]

# --- v12A1: pow inputs (base, exponent) ---
pow_inputs = [
    (2.0, 0.5), (2.0, 10.0), (2.0, -1.0), (2.0, 0.1),
    (3.0, 0.5), (10.0, 0.5), (10.0, 3.0), (10.0, -2.0),
    (0.5, 0.5), (0.5, 3.0), (100.0, 0.25),
    (1.5, 2.5), (2.718281828459045, 0.5),
    (7.0, 3.0), (7.0, -1.0), (7.0, 0.3333333333333333),
]


def to_double_str(mpf_val):
    f = float(mpf_val)
    if f != f:
        return "NAN"
    if f == float('inf'):
        return "INFINITY"
    if f == float('-inf'):
        return "-INFINITY"
    return f"{f:.17e}"


def generate_header():
    lines = [
        "/* Auto-generated by scripts/oracles/generate_oracles.py */",
        "/* MATHLIB_V12A1_ORACLE_EXPANSION */",
        "#ifndef MATHLIB_ORACLE_DATA_H",
        "#define MATHLIB_ORACLE_DATA_H",
        "",
        '#include "ml_core.h"',
        "#include <math.h>",
        "",
        "typedef struct { double input; double expected; } oracle_entry_t;",
        "typedef struct { double base; double exponent; double expected; } oracle_pow_entry_t;",
        "",
    ]

    # sin (original + large-arg)
    all_sin = trig_inputs + large_trig_inputs
    lines.append(f"static const oracle_entry_t oracle_sin[] = {{")
    for x in all_sin:
        lines.append(f"    {{{x:.17e}, {to_double_str(sin(mpf(x)))}}},")
    lines.append("};")
    lines.append(f"static const int oracle_sin_count = {len(all_sin)};")
    lines.append("")

    # cos (original + large-arg)
    all_cos = trig_inputs + large_trig_inputs
    lines.append(f"static const oracle_entry_t oracle_cos[] = {{")
    for x in all_cos:
        lines.append(f"    {{{x:.17e}, {to_double_str(cos(mpf(x)))}}},")
    lines.append("};")
    lines.append(f"static const int oracle_cos_count = {len(all_cos)};")
    lines.append("")

    # exp
    lines.append(f"static const oracle_entry_t oracle_exp[] = {{")
    for x in pos_inputs:
        lines.append(f"    {{{x:.17e}, {to_double_str(exp(mpf(x)))}}},")
    lines.append("};")
    lines.append(f"static const int oracle_exp_count = {len(pos_inputs)};")
    lines.append("")

    # log
    lines.append(f"static const oracle_entry_t oracle_log[] = {{")
    for x in pos_inputs:
        lines.append(f"    {{{x:.17e}, {to_double_str(log(mpf(x)))}}},")
    lines.append("};")
    lines.append(f"static const int oracle_log_count = {len(pos_inputs)};")
    lines.append("")

    # gamma
    lines.append(f"static const oracle_entry_t oracle_gamma[] = {{")
    for x in gamma_inputs:
        lines.append(f"    {{{x:.17e}, {to_double_str(gamma(mpf(x)))}}},")
    lines.append("};")
    lines.append(f"static const int oracle_gamma_count = {len(gamma_inputs)};")
    lines.append("")

    # lgamma (log|gamma(x)|)
    lines.append(f"static const oracle_entry_t oracle_lgamma[] = {{")
    for x in lgamma_inputs:
        g = gamma(mpf(x))
        lg = log(abs(g))
        lines.append(f"    {{{x:.17e}, {to_double_str(lg)}}},")
    lines.append("};")
    lines.append(f"static const int oracle_lgamma_count = {len(lgamma_inputs)};")
    lines.append("")

    # pow
    lines.append(f"static const oracle_pow_entry_t oracle_pow[] = {{")
    for base, exponent in pow_inputs:
        result = power(mpf(base), mpf(exponent))
        lines.append(f"    {{{base:.17e}, {exponent:.17e}, {to_double_str(result)}}},")
    lines.append("};")
    lines.append(f"static const int oracle_pow_count = {len(pow_inputs)};")
    lines.append("")

    lines.append("#endif")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    print("Generating v12A1 expanded oracle data (mpmath ground truth)...")
    header = generate_header()
    with open("tests/oracle_data.h", "w") as f:
        f.write(header)
    print("Oracle data written to tests/oracle_data.h")
'''

NEW_TEST_ORACLE = r'''/*
* MathLib v12A1: Differential Semantic Test (Oracle Validation)
* MATHLIB_V12A1_ORACLE_EXPANSION
*
* Validates: sin, cos, exp, log, gamma, lgamma, pow
* against mpmath ground truth.
*/
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "ml_core.h"
#include "ml_trig.h"
#include "ml_exp_log.h"
#include "ml_integral.h"

#ifdef MATHLIB_HAS_ORACLE_DATA
#include "oracle_data.h"
#endif

static uint64_t ulp_distance(double a, double b) {
    uint64_t ia, ib;
    memcpy(&ia, &a, sizeof(uint64_t));
    memcpy(&ib, &b, sizeof(uint64_t));
    if (ia >> 63) ia = 0x8000000000000000ULL - ia;
    if (ib >> 63) ib = 0x8000000000000000ULL - ib;
    return ia > ib ? ia - ib : ib - ia;
}

int main() {
#ifdef MATHLIB_HAS_ORACLE_DATA
    int passed = 0;
    int failed = 0;
    int64_t max_ulp = 0;
    double worst_x = 0;
    const char* worst_func = "";

    printf("=========================================================\n");
    printf("   MATHLIB v12A1: ORACLE VALIDATION (mpmath ground truth)\n");
    printf("=========================================================\n");

    /* --- sin --- */
    printf("--- ml_sin vs mpmath oracle (%d entries) ---\n", oracle_sin_count);
    for (int i = 0; i < oracle_sin_count; i++) {
        double got = ml_sin(oracle_sin[i].input);
        double exp_val = oracle_sin[i].expected;
        if (ml_isnan(exp_val) && ml_isnan(got)) { passed++; continue; }
        if (ml_isinf(exp_val) && ml_isinf(got)) { passed++; continue; }
        int64_t ulp = (int64_t)ulp_distance(got, exp_val);
        if (ulp > max_ulp) { max_ulp = ulp; worst_x = oracle_sin[i].input; worst_func = "sin"; }
        if (ulp <= 5) { passed++; }
        else {
            failed++;
            printf("  [FAIL] sin(%.17e): got %.17e expected %.17e (%lld ULP)\n",
                   oracle_sin[i].input, got, exp_val, (long long)ulp);
        }
    }

    /* --- cos --- */
    printf("--- ml_cos vs mpmath oracle (%d entries) ---\n", oracle_cos_count);
    for (int i = 0; i < oracle_cos_count; i++) {
        double got = ml_cos(oracle_cos[i].input);
        double exp_val = oracle_cos[i].expected;
        if (ml_isnan(exp_val) && ml_isnan(got)) { passed++; continue; }
        if (ml_isinf(exp_val) && ml_isinf(got)) { passed++; continue; }
        int64_t ulp = (int64_t)ulp_distance(got, exp_val);
        if (ulp > max_ulp) { max_ulp = ulp; worst_x = oracle_cos[i].input; worst_func = "cos"; }
        if (ulp <= 5) { passed++; }
        else {
            failed++;
            printf("  [FAIL] cos(%.17e): got %.17e expected %.17e (%lld ULP)\n",
                   oracle_cos[i].input, got, exp_val, (long long)ulp);
        }
    }

    /* --- exp --- */
    printf("--- ml_exp vs mpmath oracle (%d entries) ---\n", oracle_exp_count);
    for (int i = 0; i < oracle_exp_count; i++) {
        double got = ml_exp(oracle_exp[i].input);
        double exp_val = oracle_exp[i].expected;
        if (ml_isnan(exp_val) && ml_isnan(got)) { passed++; continue; }
        if (ml_isinf(exp_val) && ml_isinf(got)) { passed++; continue; }
        if (exp_val == 0.0 && got == 0.0) { passed++; continue; }
        int64_t ulp = (int64_t)ulp_distance(got, exp_val);
        if (ulp > max_ulp) { max_ulp = ulp; worst_x = oracle_exp[i].input; worst_func = "exp"; }
        if (ulp <= 5) { passed++; }
        else {
            failed++;
            printf("  [FAIL] exp(%.17e): got %.17e expected %.17e (%lld ULP)\n",
                   oracle_exp[i].input, got, exp_val, (long long)ulp);
        }
    }

    /* --- log --- */
    printf("--- ml_log vs mpmath oracle (%d entries) ---\n", oracle_log_count);
    for (int i = 0; i < oracle_log_count; i++) {
        double got = ml_log(oracle_log[i].input);
        double exp_val = oracle_log[i].expected;
        if (ml_isnan(exp_val) && ml_isnan(got)) { passed++; continue; }
        if (ml_isinf(exp_val) && ml_isinf(got)) { passed++; continue; }
        int64_t ulp = (int64_t)ulp_distance(got, exp_val);
        if (ulp > max_ulp) { max_ulp = ulp; worst_x = oracle_log[i].input; worst_func = "log"; }
        if (ulp <= 5) { passed++; }
        else {
            failed++;
            printf("  [FAIL] log(%.17e): got %.17e expected %.17e (%lld ULP)\n",
                   oracle_log[i].input, got, exp_val, (long long)ulp);
        }
    }

    /* --- gamma (v12A1) --- */
    printf("--- ml_gamma_new vs mpmath oracle (%d entries) ---\n", oracle_gamma_count);
    for (int i = 0; i < oracle_gamma_count; i++) {
        double got = ml_gamma_new(oracle_gamma[i].input);
        double exp_val = oracle_gamma[i].expected;
        if (ml_isnan(exp_val) && ml_isnan(got)) { passed++; continue; }
        if (ml_isinf(exp_val) && ml_isinf(got)) { passed++; continue; }
        if (exp_val == 0.0 && got == 0.0) { passed++; continue; }
        int64_t ulp = (int64_t)ulp_distance(got, exp_val);
        if (ulp > max_ulp) { max_ulp = ulp; worst_x = oracle_gamma[i].input; worst_func = "gamma"; }
        if (ulp <= 5) { passed++; }
        else {
            failed++;
            printf("  [FAIL] gamma(%.17e): got %.17e expected %.17e (%lld ULP)\n",
                   oracle_gamma[i].input, got, exp_val, (long long)ulp);
        }
    }

    /* --- lgamma (v12A1) --- */
    printf("--- ml_lgamma vs mpmath oracle (%d entries) ---\n", oracle_lgamma_count);
    for (int i = 0; i < oracle_lgamma_count; i++) {
        double got = ml_lgamma(oracle_lgamma[i].input);
        double exp_val = oracle_lgamma[i].expected;
        if (ml_isnan(exp_val) && ml_isnan(got)) { passed++; continue; }
        if (ml_isinf(exp_val) && ml_isinf(got)) { passed++; continue; }
        int64_t ulp = (int64_t)ulp_distance(got, exp_val);
        if (ulp > max_ulp) { max_ulp = ulp; worst_x = oracle_lgamma[i].input; worst_func = "lgamma"; }
        if (ulp <= 5) { passed++; }
        else {
            failed++;
            printf("  [FAIL] lgamma(%.17e): got %.17e expected %.17e (%lld ULP)\n",
                   oracle_lgamma[i].input, got, exp_val, (long long)ulp);
        }
    }

    /* --- pow (v12A1) --- */
    printf("--- ml_pow vs mpmath oracle (%d entries) ---\n", oracle_pow_count);
    for (int i = 0; i < oracle_pow_count; i++) {
        double got = ml_pow(oracle_pow[i].base, oracle_pow[i].exponent);
        double exp_val = oracle_pow[i].expected;
        if (ml_isnan(exp_val) && ml_isnan(got)) { passed++; continue; }
        if (ml_isinf(exp_val) && ml_isinf(got)) { passed++; continue; }
        if (exp_val == 0.0 && got == 0.0) { passed++; continue; }
        int64_t ulp = (int64_t)ulp_distance(got, exp_val);
        if (ulp > max_ulp) { max_ulp = ulp; worst_x = oracle_pow[i].base; worst_func = "pow"; }
        if (ulp <= 5) { passed++; }
        else {
            failed++;
            printf("  [FAIL] pow(%.17e, %.17e): got %.17e expected %.17e (%lld ULP)\n",
                   oracle_pow[i].base, oracle_pow[i].exponent, got, exp_val, (long long)ulp);
        }
    }

    /* --- Large-argument domain checks (Payne-Hanek) --- */
    printf("--- Large-argument domain checks (Payne-Hanek) ---\n");
    {
        double large_vals[] = {1e10, 1e15, 1e20, 1e50, 1e100, 1e200, 1e300};
        for (int i = 0; i < 7; i++) {
            double s = ml_sin(large_vals[i]);
            double c = ml_cos(large_vals[i]);
            if (!ml_isnan(s) && !ml_isinf(s) && !ml_isnan(c) && !ml_isinf(c)) {
                passed += 2;
            } else {
                failed += 2;
                printf("  [FAIL] sin/cos(%.1e) not finite\n", large_vals[i]);
            }
            /* Pythagorean identity */
            double pyth = s * s + c * c;
            if (ml_fabs(pyth - 1.0) < 1e-12) {
                passed++;
            } else {
                failed++;
                printf("  [FAIL] sin^2+cos^2 at %.1e = %.17e\n", large_vals[i], pyth);
            }
        }
    }

    printf("\n=========================================================\n");
    printf("ORACLE SUMMARY: %d passed, %d failed\n", passed, failed);
    printf("Worst case: %s(%.17e) = %lld ULP\n", worst_func, worst_x, (long long)max_ulp);
    if (max_ulp <= 5) {
        printf("VERIFIED: All functions within <= 5 ULP of mpmath ground truth.\n");
    } else {
        printf("WARNING: Maximum ULP error exceeds 5. Review worst case above.\n");
    }
    printf("=========================================================\n");
    return failed > 0 ? 1 : 0;
#else
    printf("=========================================================\n");
    printf("   MATHLIB v12A1: ORACLE VALIDATION (SKIPPED)\n");
    printf("=========================================================\n");
    printf("Oracle data not found. Generate it first:\n");
    printf("  pip install mpmath\n");
    printf("  python3 scripts/oracles/generate_oracles.py\n");
    printf("Then recompile with: -DMATHLIB_HAS_ORACLE_DATA\n");
    printf("=========================================================\n");
    return 0;
#endif
}
'''


def fail(message: str) -> None:
    print("ERROR: " + message)
    sys.exit(1)


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(content)
    print(f"  [write] {path}")


def locate_v12a1() -> tuple[Path, Path]:
    root = Path.cwd()
    candidate = root / "v12A1"
    if candidate.is_dir():
        return root, candidate
    if (root / "scripts" / "oracles").is_dir():
        print("  [note] Running from inside v12A1.")
        return root.parent, root
    fail("Run from the folder that CONTAINS v12A1/, or from inside v12A1/ itself.")


def patch_generator(v12: Path, force: bool) -> None:
    path = v12 / "scripts" / "oracles" / "generate_oracles.py"
    if path.exists() and not force:
        text = path.read_text(encoding="utf-8")
        if MARKER in text:
            print(f"  [skip] {path}: already expanded")
            return
    write_text(path, NEW_GENERATE_ORACLES)


def regenerate_oracle(v12: Path) -> bool:
    """Run the oracle generator to produce oracle_data.h."""
    gen_script = v12 / "scripts" / "oracles" / "generate_oracles.py"
    if not gen_script.exists():
        fail(f"Generator not found: {gen_script}")
    print("  [run] generate_oracles.py ...")
    result = subprocess.run(
        [sys.executable, str(gen_script)],
        cwd=str(v12),
        capture_output=True,
        text=True,
        timeout=120,
    )
    if result.returncode != 0:
        print(f"  [error] Generator failed:")
        print(result.stderr[-1000:] if result.stderr else result.stdout[-1000:])
        return False
    print(f"  [ok] {result.stdout.strip()}")
    return True


def patch_test_oracle(v12: Path, force: bool) -> None:
    path = v12 / "tests" / "test_oracle.c"
    if path.exists() and not force:
        text = path.read_text(encoding="utf-8")
        if MARKER in text:
            print(f"  [skip] {path}: already expanded")
            return
    write_text(path, NEW_TEST_ORACLE)


def archive_self(v12: Path, force: bool) -> None:
    try:
        source = Path(__file__).resolve()
        dest = v12 / "scripts" / "v12a1" / source.name
        if source == dest:
            return
        if dest.exists() and not force:
            print(f"  [skip] {dest}: already archived")
            return
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, dest)
        print(f"  [archive] {dest}")
    except NameError:
        pass


def main() -> int:
    force = "--force" in sys.argv[1:]
    root, v12 = locate_v12a1()

    print("=========================================================")
    print("  MATHLIB v12A1: ORACLE EXPANSION")
    print("=========================================================")
    print(f"  Root:  {root}")
    print(f"  v12A1: {v12}")
    print(f"  Force: {force}")
    print("---------------------------------------------------------")

    print("\n[1/3] generate_oracles.py — expanded generator")
    patch_generator(v12, force)

    print("\n[2/3] Regenerating oracle_data.h")
    if not regenerate_oracle(v12):
        print("\n  Oracle generation failed. Fix mpmath installation and retry.")
        return 1

    print("\n[3/3] test_oracle.c — expanded validator")
    patch_test_oracle(v12, force)

    archive_self(v12, force)

    print("\n---------------------------------------------------------")
    print("  Oracle expansion complete.")
    print("")
    print("  New oracle coverage:")
    print("    - gamma: 19 entries (positive + negative non-integer)")
    print("    - lgamma: 16 entries")
    print("    - pow: 16 entries (fractional + integer exponents)")
    print("    - large-arg trig: 7 entries (1e10 through 1e300)")
    print("    - Pythagorean identity at each large argument")
    print("")
    print("  Verify:")
    print("    cd v12A1")
    print("    cmake -B build && cmake --build build")
    print("")
    print("    # Compile and run oracle:")
    print("    gcc -std=c99 -O3 -fPIE \\")
    print("      -Iinclude/mathlib -Isrc \\")
    print("      -DMATHLIB_HAS_ORACLE_DATA \\")
    print("      -o build/oracle_check \\")
    print("      tests/test_oracle.c \\")
    print("      -Lbuild -lmathc -lm")
    print("    ./build/oracle_check")
    print("")
    print("  Next: 01b_minimax_ulp_fix.py (or 14_simd_evaluation.py)")
    print("=========================================================")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
